### ISSUE TITLE
Which datasets is the pretrained model trained with?

### ISSUE THREAD

**Issue by gh18l** [researchmm/SiamDW#35]
The repository gives some pretrained model, Are they only trained with VOT, OTB, and GOT10K?

**Comment by JudasDie** [comment]
> The repository gives some pretrained model, Are they only trained with VOT, OTB, and GOT1

Thanks for your interest. The testing model has been tested on OTB/VOT/GOT10K/VISDRONE/LaSOT. Please use SiamFCRes22W to test it. If you mean pretrained model for training, it's be trained on Imagenet.

**Comment by gh18l** [comment]
@JudasDie Sorry, this is a typo,  I mean which datasets the released testing models were trained with? There are only a few released models, but I can find many evaluation results in different datasets

**Comment by JudasDie** [comment]
> @JudasDie Sorry, this is a typo, I mean which datasets the released testing models were trained with? There are only a few released models, but I can find many evaluation results in different datasets

SiamFC based models are trained with VID or GOT10k, as the two tables shown in `readme.md`. SiamRPN based model are trained with VID and YTB. Besides, I provide many processed datasets, e.t VID, YTB, COCO, DET, GOT10K, LASOT, and you can try which is better for your work. BTW, SiamFCRes22W trained on GOT10K  performs best among the presented models. You can try that. You can also try more data except for GOT10k, since it's hard to say which data is better for a model.

**Comment by gh18l** [comment]
@JudasDie Thank you! I will train some models with different datasets to evaluate corresponding performance.

**Comment by JudasDie** [comment]
> @JudasDie Thank you! I will train some models with different datasets to evaluate corresponding performance.

You'r welcome. Please use tuning toolkit after testing each epoch. You can email me (zhangzhipeng2017@ia.ac.cn) for other questions. This issue will be closed.
