### ISSUE TITLE
VOT17 eao results

### ISSUE THREAD

**Issue by amoskalev** [researchmm/SiamDW#87]
Hi, thanks for your work,

I used CIResNet22FC_G.pth model to test on VOT17 benchmark with get_eao.m for evaluation. For now I have a result around 0.243 while it should be 0.266. Do you have any ideas what could go wrong?

P.S. I used hyperparameters from SiamFCRes22.yaml,
Thanks!

**Comment by JudasDie** [comment]
> Hi, thanks for your work,
> 
> I used CIResNet22FC_G.pth model to test on VOT17 benchmark with get_eao.m for evaluation. For now I have a result around 0.243 while it should be 0.266. Do you have any ideas what could go wrong?
> 
> P.S. I used hyperparameters from SiamFCRes22.yaml,
> Thanks!

Hi, thanks for your interest. The hyperparameters are used for the checkpoint of xx_V (original models). I will provide parameters for the additional model, i.e. xx_G.pth later.  I will give you a notice after uploading it.

**Comment by JudasDie** [comment]
> Hi, thanks for your work,
> 
> I used CIResNet22FC_G.pth model to test on VOT17 benchmark with get_eao.m for evaluation. For now I have a result around 0.243 while it should be 0.266. Do you have any ideas what could go wrong?
> 
> P.S. I used hyperparameters from SiamFCRes22.yaml,
> Thanks!

Hi, I have uploaded the hyper-parameters of some newly added models. Since some parameters are missing, I will update it later when I found them. But in case hampering your research, you could use the hyper-parameters I just uploaded (see readme.md). The model and parameters are best performing Res22W.
![image](https://user-images.githubusercontent.com/24988988/83356812-5db8e980-a31d-11ea-8295-13db4325b908.png) 
We hope this could help you.
